# Generated by Django 5.0 on 2023-12-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_description_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa'),
        ),
    ]
