# Generated by Django 5.0 on 2023-12-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
    ]
