# Generated by Django 5.0 on 2023-12-30 20:42

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_technology_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
