# Generated by Django 5.0 on 2023-12-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_experience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='accounts.technology'),
        ),
    ]
