# Generated by Django 5.0 on 2023-12-30 21:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_experience_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technology',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to=settings.AUTH_USER_MODEL),
        ),
    ]
