name: Django CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest

    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy using SSH
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASS }}
          connect_timeout: 30s
          last_ssh: |
            cd /root/fbg-pa
            git fetch
            git reset --hard origin/main
            git pull
            docker-compose -f docker-compose-prod.yml up --build -d
            docker-compose -f docker-compose-prod.yml ps
            
